version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: connectevent
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: connectevent
      MARIADB_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3306
      MYSQL_UNIX_PORT: 3306
    ports:
      - 3312:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--silent",
          "-h",
          "localhost",
          "-u",
          "connectevent",
          "-ppassword",
        ]
      timeout: 20s
      retries: 10

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dev/:/etc/nginx/conf.d/
