spring:
  datasource:
    url: jdbc:mariadb://localhost:3312/connectevent?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: connectevent
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

jwt:
  key: 0190ab45-7e42-7a3f-9dec-726ddf778076
  expiration:
    # 7일
    access-token: 604800000
    # 30일
    refresh-token: 2592000000

#Logging
logging:
  level:
    io.connectevent.connectevent: DEBUG

swagger:
  base-url: http://localhost:8080
